// app.js
// This is the entry point file for Hostinger Node.js deployment.
// It runs the compiled server from dist/server.cjs which is generated by the postinstall build process.
require('./dist/server.cjs');
